arrowParens: always
bracketSameLine: true
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
jsxSingleQuote: true
plugins:
  - prettier-plugin-tailwindcss
printWidth: 100
quoteProps: as-needed
semi: true
singleAttributePerLine: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
